version: "3.7"

services:
  mongo:
    image: mongo:4
    restart: ${RESTART}
    volumes:
      - ./database:/data/db
    ports:
      - ${MONGO_PORT}:27017

  nginx:
    image: nginx
    restart: ${RESTART}
    ports:
      - ${HTTP_PORT}:80
    volumes:
      - ./frontend/dist:/var/www/public
      - ./etc/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  redis:
    image: redis
    restart: ${RESTART}
    ports:
      - ${REDIS_PORT}:6379

  backend:
    image: node
    restart: ${RESTART}
    ports:
      - ${BACKEND_PORT}:3000
      - ${BACKEND_DEBUG_PORT}:9229
    depends_on:
      - mongo
      - redis
    volumes:
      - ./backend:/var/www
    working_dir: /var/www
    environment:
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DB=wbsync
      - REDIS=redis
    command: npm run start

  orders_updater:
    image: node:15-alpine
    depends_on:
      - mongo
    volumes:
      - ./syncer:/var/www
    working_dir: /var/www
    environment:
      - MONGO_HOST=mongo
      - MONGO_DB=wbsync
      - FULL_UPDATE=${FULL_UPDATE}
      - DEBUG=${DEBUG}
    command: npm run orders

  stocks_updater:
    image: node:15-alpine
    depends_on:
      - mongo
    volumes:
      - ./syncer:/var/www
      - ./backend/modules:/var/www/backend_modules
      - ${STOCKS_IMPORT_FOLDER}:/var/www/import
    working_dir: /var/www
    environment:
      - MONGO_HOST=mongo
      - MONGO_DB=wbsync
      - DEBUG=${DEBUG}
      - JSON_PATH=${STOCKS_IMPORT_CONTAINER_PATH}
    command: npm run stocks

  updater:
    image: node:15-alpine
    restart: ${RESTART}
    ports:
      - ${UPDATER_DEBUG_PORT}:9229
    depends_on:
      - mongo
      - redis
    volumes:
      - ./syncer:/var/www
      - ${STOCKS_IMPORT_FOLDER}:/var/www/import
    working_dir: /var/www
    environment:
      - MONGO_HOST=mongo
      - MONGO_DB=wbsync
      - DEBUG=${DEBUG}
      - JSON_PATH=${STOCKS_IMPORT_CONTAINER_PATH}
      - FULL_UPDATE=1
      - REDIS=redis
    command: npm run job